# -*- coding: utf-8 -*-
"""streamlit_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vq_DQRnZFq1zXLX0aKYbKoYgZ5d2JD0l
"""

# streamlit_app.py
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

# Page config
st.set_page_config(
    page_title="Airline Delay Dashboard",
    page_icon="✈️",
    layout="wide"
)

# Title
st.title(" Airline Delay Analysis Dashboard")
st.markdown("**Student:** SAEID ASHRAFIZAVEH | **Course:** Data Visualization")

# Generate data (same as your notebook)
@st.cache_data
def generate_data():
    np.random.seed(42)
    n_flights = 50000
    dates = pd.date_range('2018-01-01', '2018-01-31', periods=n_flights)

    df = pd.DataFrame({
        'FL_DATE': dates,
        'OP_CARRIER': np.random.choice(['AA', 'DL', 'UA', 'WN', 'AS', 'B6'], n_flights),
        'ORIGIN': np.random.choice(['ATL', 'ORD', 'DFW', 'LAX', 'JFK'], n_flights),
        'DEP_DELAY': np.random.normal(5, 15, n_flights),
        'ARR_DELAY': np.random.normal(4, 12, n_flights),
        'CANCELLED': np.random.choice([0, 0, 0, 0, 1], n_flights),
    })

    # Add delay causes
    for col in ['CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY']:
        df[col] = np.random.exponential(2, n_flights)

    df['DAY_NAME'] = df['FL_DATE'].dt.day_name()
    df['DAY_OF_MONTH'] = df['FL_DATE'].dt.day
    df['DEP_HOUR'] = np.random.randint(5, 22, n_flights)

    return df

df = generate_data()

# Sidebar filters
st.sidebar.header(" Filters")
airline_filter = st.sidebar.multiselect(
    "Select Airlines:",
    df['OP_CARRIER'].unique(),
    default=df['OP_CARRIER'].unique()[:4]
)

# Apply filter
if airline_filter:
    filtered_df = df[df['OP_CARRIER'].isin(airline_filter)]
else:
    filtered_df = df

# Metrics
col1, col2, col3, col4 = st.columns(4)
col1.metric("Total Flights", f"{len(filtered_df):,}")
col2.metric("Avg Delay", f"{filtered_df['DEP_DELAY'].mean():.1f} min")
col3.metric("On-Time Rate", f"{(filtered_df['DEP_DELAY'] <= 0).mean()*100:.1f}%")
col4.metric("Cancel Rate", f"{filtered_df['CANCELLED'].mean()*100:.2f}%")

# Charts
st.subheader(" Analysis Charts")

col1, col2 = st.columns(2)

with col1:
    airline_avg = filtered_df.groupby('OP_CARRIER')['DEP_DELAY'].mean().sort_values()
    fig = px.bar(airline_avg, x=airline_avg.index, y=airline_avg.values,
                 title="Average Delay by Airline",
                 labels={'x': 'Airline', 'y': 'Average Delay (minutes)'})
    st.plotly_chart(fig, use_container_width=True)

with col2:
    fig = px.pie(filtered_df, names='DAY_NAME', title='Flights by Day of Week')
    st.plotly_chart(fig, use_container_width=True)

# More charts
col1, col2 = st.columns(2)
with col1:
    hourly_delays = filtered_df.groupby('DEP_HOUR')['DEP_DELAY'].mean()
    fig = px.line(x=hourly_delays.index, y=hourly_delays.values,
                 title="Average Delay by Hour of Day",
                 labels={'x': 'Hour', 'y': 'Avg Delay (min)'})
    st.plotly_chart(fig, use_container_width=True)

with col2:
    delay_causes = ['CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY']
    cause_totals = filtered_df[delay_causes].sum()
    fig = px.pie(values=cause_totals.values,
                 names=['Carrier', 'Weather', 'NAS', 'Security', 'Late Aircraft'],
                 title='Delay Causes Breakdown')
    st.plotly_chart(fig, use_container_width=True)

# Footer
st.markdown("---")
st.caption("Final Project - Data Visualization | Created by SAEID ASHRAFIZAVEH")